spring:
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    locale: zh_CN
    time-zone: GMT+8
    property-naming-strategy: SNAKE_CASE
quiet:
  web:
    controller-prefix-configs:
#      -
#        prefix: 'system'
#        pattern: '**.controller.system.*'