spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/quiet
    username: root
    password: KV753t0PpVmpjd2d
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  data:
    redis:
      repositories:
        enabled: false
quiet:
  dev: true
  admin-username: admin
  admin-password: hVr37Kqc5C9xkkHaNmEe
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    com.blazebit.annotation.AnnotationUtils: ERROR
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE