spring:
  data:
    redis:
      host: 127.0.0.1
      database: 0
      port: 6379
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      host: 127.0.0.1
      database: 0
      port: 6379